### ISSUE TITLE
Updatable packages are not highlighted

### ISSUE THREAD

**Issue by limenote135** [marius-h/flutter_enhancement_suite#154]
**Describe the bug**

Updatable packages are not highlighted since v1.5.0.

**Steps to Reproduce**

Just open pubspec.yaml

**Expected behavior**

highlight updatable packages and show 'Update Package' menu.

**Screenshots**
![bug](https://user-images.githubusercontent.com/17950108/130979298-70e5333e-5730-48c1-b44e-d5bee42c0b2d.png)
![bug2](https://user-images.githubusercontent.com/17950108/130979324-ff35762a-1a9e-4dc3-b802-2a7d10946e15.png)

**Software used**

```
Android Studio Arctic Fox | 2020.3.1 Patch1
Build: #AI-203.7717.56.2031.7621141
Runtime version: 11.0.10+0-b96-7249189 amd64
```

**Additional context**

Following logs are shown in idea.log, but I'm not sure this is caused by this issue.
```
2021-08-26 22:56:11,641 [ 349284]  ERROR - t.daemon.impl.ExternalToolPass - IdeaLoggingEvent[message=ExternalToolPass: , throwable=com.intellij.diagnostic.PluginException: annotator: de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator@6b3a160e (class de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator) [Plugin: de.mariushoefler.flutter_enhancement_suite]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:337)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:59)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:255)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:180)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:270)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:658)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:610)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:65)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:254)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:179)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:238)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:376)
	at com.intellij.util.Alarm$Request.run(Alarm.java:362)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:208)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.util.NoSuchElementException: Collection contains no element matching the predicate.
	at de.mariushoefler.flutterenhancementsuite.models.PubPackage.getLatestVersion(PubPackage.kt:48)
	at de.mariushoefler.flutterenhancementsuite.utils.PubApi.getPackageLatestVersion(PubApi.kt:79)
	at de.mariushoefler.flutterenhancementsuite.utils.FileParser.mapToVersionDescription(FileParser.kt:35)
	at de.mariushoefler.flutterenhancementsuite.utils.FileParser.getVersionsFromFile(FileParser.kt:21)
	at de.mariushoefler.flutterenhancementsuite.utils.FileParser.checkFile(FileParser.kt:11)
	at de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator.doAnnotate(PackageUpdateExternalAnnotator.kt:25)
	at de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator.doAnnotate(PackageUpdateExternalAnnotator.kt:19)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:204)
	... 33 more
] 
```

**Comment by marius-h** [comment]
Does this only happen for packages containing "path" in the name?

**Comment by limenote135** [comment]
Ah, it looks like so! It works fine after specifying a version instead of "path".
![version](https://user-images.githubusercontent.com/17950108/131316422-6c96d85b-affd-411f-acd9-93393b6290bb.png)

**Comment by albemala** [comment]
I have the same problem as well, with these 2 exceptions in IntelliJ:

```
com.intellij.diagnostic.PluginException: annotator: de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator@76e75ad0 (class de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator) [Plugin: de.mariushoefler.flutter_enhancement_suite]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:274)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:91)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.process(ExternalToolPass.java:256)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:207)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$0(ExternalToolPass.java:180)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.runChangeAware(ExternalToolPass.java:271)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.lambda$run$2(ExternalToolPass.java:180)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:270)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.runUnderDisposeAwareIndicator(BackgroundTaskUtil.java:248)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass$1.run(ExternalToolPass.java:179)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:333)
	at com.intellij.util.ui.update.MergingUpdateQueue.execute(MergingUpdateQueue.java:323)
	at com.intellij.util.ui.update.MergingUpdateQueue.lambda$flush$1(MergingUpdateQueue.java:273)
	at com.intellij.util.ui.update.MergingUpdateQueue.flush(MergingUpdateQueue.java:287)
	at com.intellij.util.ui.update.MergingUpdateQueue.run(MergingUpdateQueue.java:242)
	at com.intellij.util.concurrency.QueueProcessor.runSafely(QueueProcessor.java:240)
	at com.intellij.util.Alarm$Request.runSafely(Alarm.java:391)
	at com.intellij.util.Alarm$Request.run(Alarm.java:377)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:220)
	at com.intellij.util.concurrency.BoundedTaskExecutor.doRun(BoundedTaskExecutor.java:216)
	at com.intellij.util.concurrency.BoundedTaskExecutor.access$200(BoundedTaskExecutor.java:27)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.execute(BoundedTaskExecutor.java:195)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:213)
	at com.intellij.util.concurrency.BoundedTaskExecutor$1.run(BoundedTaskExecutor.java:184)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)
```

```
Caused by: de.mariushoefler.flutterenhancementsuite.exceptions.GetLatestPackageVersionException: Cannot get the latest version number for package: msix_version
	at de.mariushoefler.flutterenhancementsuite.utils.PubApi.getPackageLatestVersion(PubApi.kt:85)
	at de.mariushoefler.flutterenhancementsuite.utils.FileParser.mapToVersionDescription(FileParser.kt:35)
	at de.mariushoefler.flutterenhancementsuite.utils.FileParser.getVersionsFromFile(FileParser.kt:21)
	at de.mariushoefler.flutterenhancementsuite.utils.FileParser.checkFile(FileParser.kt:11)
	at de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator.doAnnotate(PackageUpdateExternalAnnotator.kt:25)
	at de.mariushoefler.flutterenhancementsuite.inspections.PackageUpdateExternalAnnotator.doAnnotate(PackageUpdateExternalAnnotator.kt:19)
	at com.intellij.codeInsight.daemon.impl.ExternalToolPass.doAnnotate(ExternalToolPass.java:204)
	... 34 more
```

## Version information

IntelliJ IDEA `2021.2.1` • Flutter plugin `io.flutter 60.0.4` • Dart plugin `212.5080.8`

Flutter 2.5.0-5.2.pre • channel beta • https://github.com/flutter/flutter.git
Framework • revision 19c61fed0d (2 weeks ago) • 2021-08-18 17:10:31 -0700
Engine • revision 7a4c4505f6
Tools • Dart 2.14.0 (build 2.14.0-377.7.beta)

**Flutter Enhancement Suite 1.6.0**

**Comment by limenote135** [comment]
Any update?

**Comment by marius-h** [comment]
Fixed ✅
