### ISSUE TITLE
Unhandled exception in [StandaloneCoroutine{Cancelling}@522ac1d7, EdtCoroutineDispatcher@5343f73e]

### ISSUE THREAD

**Issue by BorzdeG** [marius-h/flutter_enhancement_suite#183]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2021.3.1 RC` • Flutter plugin `io.flutter 63.2.4` • Dart plugin `213.5744.122`

No Flutter sdk configured.

## Exception

Unhandled exception in [StandaloneCoroutine{Cancelling}@522ac1d7, EdtCoroutineDispatcher@5343f73e]

```
java.lang.NullPointerException
	at de.mariushoefler.flutterenhancementsuite.codeInsight.PubChangelogProvider.findPackageNameAndGenerateDoc(PubChangelogProvider.kt:39)
	at de.mariushoefler.flutterenhancementsuite.codeInsight.PubChangelogProvider.generateDoc(PubChangelogProvider.kt:22)
	at com.intellij.lang.documentation.CompositeDocumentationProvider.generateDoc(CompositeDocumentationProvider.java:141)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.localDoc(PsiElementDocumentationTarget.kt:72)
	at com.intellij.lang.documentation.psi.PsiElementDocumentationTarget.computeDocumentation(PsiElementDocumentationTarget.kt:58)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt:25)
	at com.intellij.lang.documentation.impl.ImplKt$computeDocumentationAsync$1$documentationResult$1.invoke(impl.kt)
	at com.intellij.openapi.progress.CancellationKt$sam$com_intellij_openapi_util_ThrowableComputable$0.compute(cancellation.kt)
	at com.intellij.openapi.progress.Cancellation.withJob(Cancellation.java:65)
	at com.intellij.openapi.progress.CancellationKt.withJob(cancellation.kt:12)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$3.run(ReadAction.kt:74)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1084)
	at com.intellij.openapi.application.rw.ReadAction.tryReadAction(ReadAction.kt:71)
	at com.intellij.openapi.application.rw.ReadAction.access$tryReadAction(ReadAction.kt:14)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2$2.run(ReadAction.kt:62)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:158)
	at com.intellij.openapi.application.rw.ReadAction$tryReadAction$2.invokeSuspend(ReadAction.kt:60)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

**Comment by vladimirfx** [comment]
Same crash - just opened non-flutter project.

## Version information

IntelliJ IDEA `2021.3.1` • Flutter plugin `io.flutter 63.2.4` • Dart plugin `213.5744.122`

No Flutter sdk configured.
