### ISSUE TITLE
PluginException: The default implementation of method 'getFile' is deprecated

### ISSUE THREAD

**Issue by wltiii** [marius-h/flutter_enhancement_suite#213]
**Describe the bug**

**Version information**
IntelliJ IDEA 2021.3 • Flutter plugin io.flutter 63.2.4 • Dart plugin 213.5744.122

**What happened**
Intellij Idea on Mac Monterey 12.3.1 boots with error:

Flutter 2.10.5 • channel stable • https://github.com/flutter/flutter.git Framework • revision 5464c5bac7 (3 weeks ago) • 2022-04-18 09:55:37 -0700 Engine • revision 57d3bac3dd Tools • Dart 2.16.2 • DevTools 2.9.2

**Exception**
null

com.intellij.diagnostic.PluginException: The default implementation of method 'getFile' is deprecated, you need to override it in 'class de.mariushoefler.flutterenhancementsuite.editor.linter.LinterEditor'. A proper @NotNull implementation required [Plugin: de.mariushoefler.flutter_enhancement_suite]
	at com.intellij.ide.plugins.PluginManagerCore.createPluginException(PluginManagerCore.java:270)
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:12)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.openapi.fileEditor.FileEditor.getFile(FileEditor.java:127)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.updateHighlighting(ScriptClassRootsUpdater.kt:249)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.doUpdate(ScriptClassRootsUpdater.kt:197)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater.doUpdate$default(ScriptClassRootsUpdater.kt:175)
	at org.jetbrains.kotlin.idea.core.script.ucache.ScriptClassRootsUpdater$ensureUpdateScheduled$$inlined$withLock$kotlin_core$lambda$1.run(ScriptClassRootsUpdater.kt:162)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.util.BackgroundTaskUtil.lambda$execute$8(BackgroundTaskUtil.java:206)
	at java.base/java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1736)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

**Comment by xuiqzy** [comment]
I believe I got the same error:

## What happened

just browsing files

## Version information

Android Studio `Electric Eel | 2022.1.1 Patch 1` • Flutter plugin `io.flutter 72.1.2` • Dart plugin `221.6096`

Flutter 3.7.3 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 9944297138 (9 days ago) • 2023-02-08 15:46:04 -0800
Engine • revision 248290d6d5
Tools • Dart 2.19.2 • DevTools 2.20.1

## Exception

null

```
com.intellij.diagnostic.PluginException: The default implementation of method 'getFile' is deprecated, you need to override it in 'class de.mariushoefler.flutterenhancementsuite.editor.linter.LinterEditor'. A proper @NotNull implementation required [Plugin: de.mariushoefler.flutter_enhancement_suite]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:83)
	at com.intellij.diagnostic.PluginException.reportDeprecatedDefault(PluginException.java:110)
	at com.intellij.openapi.fileEditor.FileEditor.getFile(FileEditor.java:135)
	at com.intellij.openapi.fileEditor.impl.text.TextEditorProvider.getDocuments(TextEditorProvider.java:189)
	at com.intellij.openapi.command.impl.UndoManagerImpl.getDocumentReferences(UndoManagerImpl.java:594)
	at com.intellij.openapi.command.impl.UndoManagerImpl.getDocRefs(UndoManagerImpl.java:583)
	at com.intellij.openapi.command.impl.UndoManagerImpl.isUndoOrRedoAvailable(UndoManagerImpl.java:463)
	at com.intellij.openapi.command.impl.UndoManagerImpl.isUndoAvailable(UndoManagerImpl.java:452)
	at com.intellij.codeInsight.daemon.impl.CanISilentlyChange.canUndo(CanISilentlyChange.java:25)
	at com.intellij.codeInsight.daemon.impl.CanISilentlyChange.thisFile(CanISilentlyChange.java:55)
	at com.intellij.codeInsight.daemon.impl.HighlightingSessionImpl.createHighlightingSession(HighlightingSessionImpl.java:107)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl.queuePassesCreation(DaemonCodeAnalyzerImpl.java:931)
	at com.intellij.codeInsight.daemon.impl.DaemonCodeAnalyzerImpl$UpdateRunnable.run(DaemonCodeAnalyzerImpl.java:897)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at com.intellij.util.concurrency.SchedulingWrapper$MyScheduledFutureTask.run(SchedulingWrapper.java:223)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:200)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
```

**Comment by atuuuu** [comment]
I also encountered it.
I think opening analysis_option.yaml triggered it

[bug-report.md](https://github.com/marius-h/flutter_enhancement_suite/files/11012189/bug-report.md)
