### ISSUE TITLE
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0

### ISSUE THREAD

**Issue by zeusbaba** [marius-h/flutter_enhancement_suite#54]
## What happened

(please describe what you were doing when this exception occurred)

## Version information

IntelliJ IDEA `2020.1.2` • Flutter plugin `io.flutter 46.0.3` • Dart plugin `201.7846.93`

Error getting Flutter sdk information.

## Exception

null

```
java.lang.ArrayIndexOutOfBoundsException: Index 1 out of bounds for length 0
	at java.base/java.util.ArrayList.add(ArrayList.java:486)
	at java.base/java.util.ArrayList.add(ArrayList.java:498)
	at de.mariushoefler.flutter_enhancement_suite.pub.DependencyChecker.getLatestVersion(DependencyChecker.kt:39)
	at de.mariushoefler.flutter_enhancement_suite.utils.FileParser.mapToVersionDescription(FileParser.kt:59)
	at de.mariushoefler.flutter_enhancement_suite.utils.FileParser.access$mapToVersionDescription(FileParser.kt:13)
	at de.mariushoefler.flutter_enhancement_suite.utils.FileParser$Companion$getVersionsFromFile$$inlined$map$lambda$1.invokeSuspend(FileParser.kt:28)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(Dispatched.kt:238)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:594)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.access$runSafely(CoroutineScheduler.kt:60)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:742)
```

**Comment by marius-h** [comment]
How can I reproduce this issue?

**Comment by zeusbaba** [comment]
thnx for your feedback.  
Unfortunately, I don't know how to reproduce it either :|  
If that issue happens again, I can share more details next time.
